version: "3"

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      - API_HOST=${API_HOST}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - /srv/app/fr-shohin-admin-server/node_modules
      - ./server:/srv/app/fr-shohin-admin-server
    command: npm run dev
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:3000
    volumes:
      - /srv/app/fr-shohin-admin-client/node_modules
      - ./client:/srv/app/fr-shohin-admin-client
    links:
      - server
    command: npm run start
